### ISSUE TITLE
Add other groups/projects?

### ISSUE THREAD

**Issue by alister** [alister/php-in-london#1]
Would it be useful to add additional pages for local User groups and even open-source projects that are based in the London area?

**Comment by romaninsh** [comment]
That would be cool. I'm running a start-up and we're working on several open-source projects that other companies on the list could benefit from. I'd like others to be able to discover what we do.

**Comment by romaninsh** [comment]
Here, i tried to format my entry. 

### Agile Toolkit Ltd,
Suite B, The Colonnade,
Station Place, Letchworth Garden City,
SG6

* http://git.io/ad (stable) and http://github.com/atk4/ui (in development)
* @atk4 and https://gitter.im/atk4/atk4

PHP Tech: Composer (compatible with all major frameworks and apps)
OSS Activity: Building Data and UI frameworks (MIT) for enterprise PHP use.
Commercial Activity: Offering commercial extensions, support and training.

**Comment by alister** [comment]
How about you make a new pull request with the new file, and we'll put it to an open vote, Yay/Nay on the PR, best of 5?

**Comment by romaninsh** [comment]
I suppose I could do that.

**Comment by craigwillis85** [comment]
I'm happy with the local user groups. I'm not sure about the open-source projects though. 

What is the idea behind it?

**Comment by romaninsh** [comment]
Created #22 with a proposal, should explain about the contents too.

@craigwillis85 to answer your note - I've been open-source author for over 10 years and I envy guys who do the same in JavaScript, Python or Ruby. Everyone there have a small yet useful project, people exchange ideas and try to collaboratively solve problems and find new approaches. 

For me PHP is not only a job, but also a hobby and I was hoping that London would have some like-minded people and I'd be thrilled to find them. Ability to meet up and work on solving a common problems or creating new interesting projects for me is much more interesting that listening to yet another Laravel presentation.

So creating groups and communities that support and educate, teach people to contribute or even how to commercialize their ideas in PHP is something I really wish we would have.

**Comment by craigwillis85** [comment]
I understand.

Would it be worth splitting up and having `Groups` and `Projects` as separate?

**Comment by romaninsh** [comment]
@craigwillis85 that's a great idea. I'll try to implement that in my PR.

**Comment by romaninsh** [comment]
I have finally found time to separate and clean things up as @craigwillis85 suggested. I have also re-formatted the "open source projects" , so that the main contributors/authors of those projects would specify which PHP events they attend. 

I hope this would to put more context behind individuals and motivate people to attend more events.

Further suggestions are welcome.

#22

**Comment by alister** [comment]
I'm not sure that projects work among this more geographically-oriented list.

There are other more generic 'Awesome PHP' list(s) - such as https://github.com/ziadoz/awesome-php which may be a better fit for them.

**Comment by alister** [comment]
groups.md created in PR #22 - though on further thought, projects aren't a good fit, as they don't easily fit into the geographical aim of these lists.

Thanks for the work on adding the groups however, @romaninsh  and @craigwillis85.
